sudo: required
dist: trusty
group: edge
services:
- docker
env:
  global:
  - secure: jm2AKgkxzwOM05AJPN8NfTNZ0zcOf80brh6/mgOj0AhfptGVlGBE9IbcB2pjv+vZbHwDk9mtmt0M8ZRgfXYDBxLmTUAOZPeoalxrH2MWFc8t07lyyBB63FVlQZDqwPogKt1lJXy7t4Zb07RwHKFWV6VMWs8p24MHNC1hK9mVgRO/3S6M95YUqJvSs6/4jYoSJuF2hgXU1Kr5WaE43MFl3Fr1A/wbYavMGy+ZVzd+/PiRzxxpBtJ1rN1l2l5pOf8+NouBkgW4IBCfYaZzkBIkmfrJieayDrn1KCw9OC2pPDamIwvJ2lk1HBlCLCJ7SYDwxmtoL6EBEJBisxwLnoqapdob699bDZao282FHL19K6wGpehljt8jYza4xW/ELOt10lYyY/egSQBX8h61+bt2cniDhhQdNFaA0huaOrwN4HkZj88qXMA7mIbyu5TkQMRvazlzEu0tzvGEu/RiVXwIFoYoveHugy3YBkk4BXw3NqIg1kxMh6TdF+SPQPwHZrC8eUQW1QCghF0ImpBU5UwDWMCwZQ6z7kwrmWPrVfv9DlzFfeZAohF8O39opUq7aFOYOvAnZKTp0FjO+ombCZJXx9q2z2VV/tSbPV3SRXF474u+J9CRJyOwfUERzRK8M4ezVwKkEq9H7tHwJUBs/RhhqaGQF0co6O8S6x1IxSRvIRw=
  - secure: HagRvIpSLY1uad/IrJypWxQKfQMi83zFvcRvNNwTNFUp0LFphFIEZjWauWLyxYMGRErhVDvMXBsbchYWbHNN72WThIJ464yqhc7kqMdOTabjeF25b645EH9Ti/v6bgdOHaUmTotu4b/7zWpm+LBbb3V2vRXjsb1NsL5sHprbNkgdVu7GbzcUMbGevE2FOVpPkY9FOjxRmwuuiO9lehKiUpzGLtqiTqJKokAobR5uC0PNJIl+Z+4B9NK3R1Ztdu1L2/UQe4I44uCI9trcWaxQAUorN8t06HIiYkA054jUN6Yh2ZPzL1I4u2o7Tt8F/XtARchqWn4RLrslEMD4zjbAr+IRixF6up4dXskjimFvI5AXjfGP3uSC+N8nP51bQeqKGFj3hzFqlXnN7QZ+UwV/cYv7/8dmbdxwpy0AD77PTGFQMjy0Wr+q8nIQaoesgKdxQiFeC1qmYbjBki0pppL49AwIcWxYNbY4jt8oc+ZefVj92DO3DvwDNwDpZhjTZNJHvRW8rmLDHQbGAap7adyT6h/ny3m52LzKue3o+9f83WsH+BDvcuKhOMJ9DraPOskbrWY0HuRIwPI67Nnk4dfemGq+hGSh/P+pndXZpbY6O3Wk6ESc5lbHkFZqVvbVCmCiAe1gLPGTSiESC5PCf9UnkF7FPvD2MZUfNix3IjYgsmg=
language: node_js
node_js:
- '6'
- '7'
addons:
  sauce_connect: true
cache:
  directories:
  - node_modules
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
- cd src/CoreDataStore.Web
script:
- npm run clean
- npm run build
after_success:
- rm -f wwwroot/index.html
- cd ../..
- docker build -f docker/node.dockerfile -t stuartshay/coredatastore:node$TRAVIS_NODE_VERSION-$TRAVIS_BUILD_NUMBER .
- docker run --env-file docker/env.staging -d -p 3000:3000 stuartshay/coredatastore:node$TRAVIS_NODE_VERSION-$TRAVIS_BUILD_NUMBER
- docker ps -a
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push stuartshay/coredatastore:node$TRAVIS_NODE_VERSION-$TRAVIS_BUILD_NUMBER;
  fi
- npm i selenium-webdriver assert mocha
- npm run selenium
notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5

# travis by gem
# travis encrypt DOCKER_USERNAME=navigatordatastore DOCKER_PASSWORD=yourPassword --add env.global
# travis encrypt SAUCE_USERNAME=navigatordatastore SAUCE_ACCESS_KEY=yourKey--add env.global
