sudo: required
dist: trusty
group: edge
services:
- docker
env:
  global:
  - secure: jm2AKgkxzwOM05AJPN8NfTNZ0zcOf80brh6/mgOj0AhfptGVlGBE9IbcB2pjv+vZbHwDk9mtmt0M8ZRgfXYDBxLmTUAOZPeoalxrH2MWFc8t07lyyBB63FVlQZDqwPogKt1lJXy7t4Zb07RwHKFWV6VMWs8p24MHNC1hK9mVgRO/3S6M95YUqJvSs6/4jYoSJuF2hgXU1Kr5WaE43MFl3Fr1A/wbYavMGy+ZVzd+/PiRzxxpBtJ1rN1l2l5pOf8+NouBkgW4IBCfYaZzkBIkmfrJieayDrn1KCw9OC2pPDamIwvJ2lk1HBlCLCJ7SYDwxmtoL6EBEJBisxwLnoqapdob699bDZao282FHL19K6wGpehljt8jYza4xW/ELOt10lYyY/egSQBX8h61+bt2cniDhhQdNFaA0huaOrwN4HkZj88qXMA7mIbyu5TkQMRvazlzEu0tzvGEu/RiVXwIFoYoveHugy3YBkk4BXw3NqIg1kxMh6TdF+SPQPwHZrC8eUQW1QCghF0ImpBU5UwDWMCwZQ6z7kwrmWPrVfv9DlzFfeZAohF8O39opUq7aFOYOvAnZKTp0FjO+ombCZJXx9q2z2VV/tSbPV3SRXF474u+J9CRJyOwfUERzRK8M4ezVwKkEq9H7tHwJUBs/RhhqaGQF0co6O8S6x1IxSRvIRw=
  - secure: VC5EYpIhm6UfhbvzD9N1nbVYdFrgJR+/S1/Tir1vINvaipmsFjqqy3KU0odO2uU15tlDXTxcHaL/vomJC4oDTEd5FElF9vcB/05N3LzdjTU/njUBDMCaDf1c9oRQ3zJhkwM2eFE/5Jak0BIFyQ+0kAwbY33aBbWtM+9aoehE6OQF592xigNR2yFu+whbYK1iPzdcfV/POQotJBlp7ImZZpxI00w1S25jh3sir/pEE3ON/WLCVJDoIrta+wzttcjVp7L4kl23ESFfkwDUAG3uJW62sGXxsgRRxmYpS7L6BzjFreUesW6LnlC0f6xMiiuhWzpJUZAjpZVHvfWyflasxltX2xFLZ71kp/Fe98ClkaxBTNh/0IOUjBVTe9iXIKudETZZCNv0p1kjzWPnds/itNjPYS/DGEshU7lKKidaLu1SSExMVZtea5y7qwnd724kWTw9iooEsWKaLlAcJ4q/fXBd5DzjwDC22HcCUmCTVoKH+RZZx3HOhLOQu02025kDBbvRbd2g4rtT9cz3/0vxgHporZ7DjyRV1OkkQBJO7eVwCiIlo38OlLljaz5OcQa/j0Uv9tmhBDw8nFfBt8pCLJXug0ImVdbP5/rp0mVWu7CLRCpCi4NGXLMP8DYXBFNn6BHCwwn5shqLFF+Uh7pApBFnhcyJh0onRxUVrVs3ZsE=
language: node_js
node_js:
- '6'
- '7'
addons:
  sauce_connect: true
cache:
  directories:
  - node_modules
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
- cd src/CoreDataStore.Web
script:
- npm run clean
- npm run build
after_success:
- rm -f wwwroot/index.html
- cd ../..
- docker build -f docker/node.dockerfile -t stuartshay/coredatastore:node$TRAVIS_NODE_VERSION-$TRAVIS_BUILD_NUMBER .
- docker run --env-file docker/env.staging -d -p 3000:3000 stuartshay/coredatastore:node$TRAVIS_NODE_VERSION-$TRAVIS_BUILD_NUMBER
- docker ps -a
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push stuartshay/coredatastore:node$TRAVIS_NODE_VERSION-$TRAVIS_BUILD_NUMBER;
  fi
- npm i selenium-webdriver assert mocha
- npm run selenium
notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5

# travis by gem
# travis encrypt DOCKER_USERNAME=navigatordatastore DOCKER_PASSWORD=yourPassword --add env.global
# travis encrypt SAUCE_USERNAME=navigatordatastore SAUCE_ACCESS_KEY=yourKey--add env.global
