version: '2'
volumes:
  database:
    external: true
    driver: 'null'
  database-export:
    external: true
    driver: 'null'
services:
  database:
    image: stuartshay/coredatastore-postgres:development
    environment:
      POSTGRES_PASSWORD: password
    stdin_open: true
    volumes:
    - database:/var/lib/postgresql/data
    - database-export:/export
    tty: true
    logging:
      driver: fluentd
      options:
        tag: docker.coredatastore.postgres
    ports:
    - 5434:5432/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  endpoint:
    image: rancher/dns-service
    links:
    - coredatastore-api:coredatastore-api
  coredatastore-api:
    image: stuartshay/coredatastore:2.1-runtime
    stdin_open: true
    tty: true
    links:
    - database:database
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  node-ui:
    image: stuartshay/coredatastore:${NODE_UI_TAG}
    environment:
      LANDMARK: https://qa-api.coredatastore.com/api/
      LOCATIONAPI: https://qa-api-location.coredatastore.com/api/
      MAPSAPI: https://api-maps.navigatorglass.com/api/
      REPORTSAPI: https://qa-reports.coredatastore.com/api/
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  coredatastore-reporting-api:
    image: stuartshay/coredatastore-reporting-api:2.0-runtime
    stdin_open: true
    tty: true
    links:
    - database:database
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  reporting:
    image: rancher/dns-service
    links:
    - coredatastore-reporting-api:coredatastore-reporting-api
  coredatastore-internal-tools:
    image: stuartshay/coredatastore-internal-tools
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  coredatastore-location-api:
    image: stuartshay/coredatastore-location-api:2.0-runtime
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://*:5200
    stdin_open: true
    tty: true
    links:
    - database:database
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
