version: '2'
volumes:
  database:
    driver: rancher-nfs
  database-export:
    driver: rancher-nfs
services:
  database:
    image: stuartshay/coredatastore-postgres:development
    environment:
      POSTGRES_PASSWORD: password
    stdin_open: true
    volumes:
    - database:/var/lib/postgresql/data
    - database-export:/export
    tty: true
    logging:
      driver: fluentd
      options:
        tag: docker.coredatastore.postgres
    ports:
    - 5432:5432/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  endpoint:
    image: rancher/dns-service
    links:
    - coredatastore-api:coredatastore-api
  coredatastore-api:
    image: stuartshay/coredatastore:2.2.2-api-circleci
    stdin_open: true
    tty: true
    links:
    - database:database
    labels:
      io.rancher.container.pull_image: always
  node-ui:
    image: stuartshay/coredatastore:node-ui
    environment:
      LANDMARK: https://api.coredatastore.com/api/
      LOCATIONAPI: https://qa-api-location.coredatastore.com/api/
      MAPSAPI: https://api-maps.navigatorglass.com/api/
      REPORTSAPI: https://reports.coredatastore.com/api/
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  coredatastore-reporting-api:
    image: stuartshay/coredatastore-reporting-api:2.0-multi
    stdin_open: true
    tty: true
    links:
    - database:database
    labels:
      io.rancher.container.pull_image: always
  reporting:
    image: rancher/dns-service
    links:
    - coredatastore-reporting-api:coredatastore-reporting-api
  coredatastore-internal-tools:
    image: stuartshay/coredatastore-internal-tools:stable
    environment:
      TERM_PASS: Navigator2017
      TERM_USER: Navigator
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  coredatastore-location-api:
    image: stuartshay/coredatastore-location-api:2.0-runtime
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://*:5200
    stdin_open: true
    tty: true
    links:
    - database:database
    labels:
      io.rancher.container.pull_image: always

