version: "3.2"

services:

  web:
    image: "stuartshay/coredatastore:nanoserver-2-1-build"
    ports:
     - "5000:5000"
    networks:
      - default

networks:
  default:
    external:
      name: nat