// <auto-generated />
using CoreDataStore.Data.SqlServer.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoreDataStore.Data.SqlServer.EF.Migrations
{
    [DbContext(typeof(Program.NycLandmarkContextMock))]
    partial class NycLandmarkContextMockModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreDataStore.Domain.Entities.Base.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EventDateUtc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ImportType")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("NewValue");

                    b.Property<string>("OriginalValue");

                    b.Property<int>("RecordId");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("CoreDataStore.Domain.Entities.Landmark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("BBL");

                    b.Property<long>("BIN_NUMBER");

                    b.Property<int>("BLOCK");

                    b.Property<string>("BOUNDARIES")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("BoroughID")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime?>("CALEN_DATE");

                    b.Property<bool>("COUNT_BLDG");

                    b.Property<string>("DESIG_ADDR")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("DESIG_DATE");

                    b.Property<string>("HIST_DISTR")
                        .HasMaxLength(200);

                    b.Property<string>("LAST_ACTIO")
                        .HasMaxLength(50);

                    b.Property<string>("LM_NAME")
                        .HasMaxLength(200);

                    b.Property<string>("LM_TYPE")
                        .HasMaxLength(19);

                    b.Property<int>("LOT");

                    b.Property<string>("LP_NUMBER")
                        .HasMaxLength(10);

                    b.Property<decimal?>("Latitude");

                    b.Property<decimal?>("Longitude");

                    b.Property<bool>("MOST_CURRE");

                    b.Property<string>("NON_BLDG")
                        .HasMaxLength(100);

                    b.Property<long?>("OBJECTID");

                    b.Property<string>("OTHER_HEAR")
                        .HasMaxLength(200);

                    b.Property<string>("PLUTO_ADDR")
                        .HasMaxLength(200);

                    b.Property<string>("PUBLIC_HEA")
                        .HasMaxLength(200);

                    b.Property<bool>("SECND_BLDG");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("STATUS_NOT")
                        .HasMaxLength(200);

                    b.Property<bool>("VACANT_LOT");

                    b.HasKey("Id");

                    b.HasIndex("LP_NUMBER");

                    b.ToTable("Landmark");
                });

            modelBuilder.Entity("CoreDataStore.Domain.Entities.LPCLamppost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Block");

                    b.Property<string>("Borough")
                        .HasMaxLength(20);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Located")
                        .HasMaxLength(100);

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("Lot");

                    b.Property<int>("PostId");

                    b.Property<string>("SubType")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("LPCLamppost");
                });

            modelBuilder.Entity("CoreDataStore.Domain.Entities.LPCLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(255);

                    b.Property<long?>("BBL");

                    b.Property<long?>("BIN");

                    b.Property<int?>("Block");

                    b.Property<string>("Borough")
                        .HasMaxLength(13);

                    b.Property<string>("LPNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("Lot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100);

                    b.Property<long?>("ObjectId");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .HasMaxLength(255);

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("LPNumber")
                        .IsUnique();

                    b.ToTable("LPCLocation");
                });

            modelBuilder.Entity("CoreDataStore.Domain.Entities.LPCReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Architect")
                        .HasMaxLength(200);

                    b.Property<string>("Borough")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DateDesignated");

                    b.Property<string>("LPCId")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("LPNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("ObjectType")
                        .HasMaxLength(50);

                    b.Property<bool>("PhotoStatus");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(500);

                    b.Property<string>("Street")
                        .HasMaxLength(200);

                    b.Property<string>("Style")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("LPCReport");
                });

            modelBuilder.Entity("CoreDataStore.Domain.Entities.Pluto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<long>("BBL");

                    b.Property<int>("Block");

                    b.Property<string>("Borough")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("HistDist");

                    b.Property<string>("LandmarkName")
                        .HasColumnName("Landmark")
                        .HasMaxLength(100);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("Lot");

                    b.Property<int>("LotArea");

                    b.Property<int>("NumBldgs");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(21);

                    b.Property<int>("XCoord");

                    b.Property<int>("YCoord");

                    b.Property<int>("YearBuilt");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Pluto");
                });

            modelBuilder.Entity("CoreDataStore.Domain.Entities.Landmark", b =>
                {
                    b.HasOne("CoreDataStore.Domain.Entities.LPCReport", "LPCReport")
                        .WithMany("Landmarks")
                        .HasForeignKey("LP_NUMBER")
                        .HasPrincipalKey("LPNumber");
                });

            modelBuilder.Entity("CoreDataStore.Domain.Entities.LPCLocation", b =>
                {
                    b.HasOne("CoreDataStore.Domain.Entities.LPCReport", "LPCReport")
                        .WithOne("LPCLocation")
                        .HasForeignKey("CoreDataStore.Domain.Entities.LPCLocation", "LPNumber")
                        .HasPrincipalKey("CoreDataStore.Domain.Entities.LPCReport", "LPNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
